/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerTipoPagamento;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import model.ModelTipoPagamento;

public class ViewPagamentoPDV extends javax.swing.JDialog {

    private float valorTotal;
    private float desconto;
    private float valorRecebido;
    private float troco;
    private float totalPagar;
    private String tipoPagamento;
    ControllerTipoPagamento controllerTipoPagamento = new ControllerTipoPagamento();
    ArrayList<ModelTipoPagamento> listaModelTipoPagamentos = new ArrayList<>();

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private int ponto = 0;
    private int ponto2 = 0;

    /**
     * Creates new form ViewPagamentoPDV
     */
    public ViewPagamentoPDV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.listarTipoPagamento();
        setLocationRelativeTo(null);
        jtfDesconto.setTransferHandler(null); //Evitar colar, recortar, etc
        jtfValorRecebido.setTransferHandler(null);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcbTipoPagamento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlfValorPagar = new javax.swing.JLabel();
        jlRS4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTroco = new javax.swing.JTextField();
        jtfSubtotal = new util.VerificarCampo("Numeros",10);
        jtfDesconto = new util.VerificarCampo("Numeros/Ponto",10);
        jtfValorRecebido = new util.VerificarCampo("Numeros/Ponto",10);

        setTitle("Pagamento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 190, 50));
        getRootPane().setDefaultButton(okButton);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pagamento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jcbTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jcbTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 350, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Desconto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Subtotal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valor Recebido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total a pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jlfValorPagar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlfValorPagar.setForeground(new java.awt.Color(0, 153, 102));
        jlfValorPagar.setText(" ");

        jlRS4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlRS4.setForeground(new java.awt.Color(0, 153, 102));
        jlRS4.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jlRS4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlfValorPagar)
                .addGap(216, 216, 216))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfValorPagar)
                    .addComponent(jlRS4))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, 547, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Troco:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 412, -1, -1));

        jtfTroco.setEditable(false);
        jtfTroco.setBackground(new java.awt.Color(255, 204, 204));
        jtfTroco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtfTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 399, 243, 44));

        jtfSubtotal.setEditable(false);
        jtfSubtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jtfSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 350, 50));

        jtfDesconto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 350, 50));

        jtfValorRecebido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValorRecebidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorRecebidoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfValorRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 350, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (this.jtfDesconto.getText().equals("")) {
            this.desconto = 0;
        } else {
            this.desconto = Float.parseFloat(this.jtfDesconto.getText());
        }
        this.valorRecebido = Float.parseFloat(this.jtfValorRecebido.getText());
        this.troco = Float.parseFloat(this.jtfTroco.getText());
        this.totalPagar = Float.parseFloat(this.jlfValorPagar.getText());
        this.tipoPagamento = jcbTipoPagamento.getSelectedItem().toString();
        if (troco < 0) {
            JOptionPane.showMessageDialog(null, "O troco não pode ser menor que 0");
        } else if (Float.parseFloat(jlfValorPagar.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "O total a pagar deve ser maior que zero");
        } else {
            doClose(RET_OK);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void jtfValorRecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorRecebidoKeyReleased
        this.jlfValorPagar.setText(String.valueOf(this.calcularDesconto()));
        this.jtfTroco.setText(String.valueOf(this.calcularTroco()));
    }//GEN-LAST:event_jtfValorRecebidoKeyReleased

    private void jtfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyReleased
        this.jlfValorPagar.setText(String.valueOf(this.calcularDesconto()));
        this.jtfTroco.setText(String.valueOf(this.calcularTroco()));
    }//GEN-LAST:event_jtfDescontoKeyReleased

    private void jtfDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyTyped
        if ((evt.getKeyChar() + "").equals(".")) {
            ponto++;
            if (ponto > 1) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfDescontoKeyTyped

    private void jtfValorRecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorRecebidoKeyTyped
        if ((evt.getKeyChar() + "").equals(".")) {
            ponto2++;
            if (ponto2 > 1) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfValorRecebidoKeyTyped

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        limparCampos();
        dispose();
    }

    private float calcularDesconto() {
        if (!jtfSubtotal.getText().trim().equals("")) {
            if (jtfDesconto.getText().isEmpty()) {
                return valorTotal = Float.parseFloat(this.jtfSubtotal.getText());
            }
            valorTotal = Float.parseFloat(this.jtfSubtotal.getText()) - Float.parseFloat(this.jtfDesconto.getText());
            return valorTotal;
        } else {
            return 0;
        }
    }

    private float calcularTroco() {
        if (!jtfValorRecebido.getText().equals("")) {
            return Float.parseFloat(this.jtfValorRecebido.getText()) - valorTotal;
        } else {
            return 0;
        }
    }

    private void listarTipoPagamento() {
        listaModelTipoPagamentos = controllerTipoPagamento.getListaTipoPagamentoController();
        jcbTipoPagamento.removeAllItems();
        for (int i = 0; i < listaModelTipoPagamentos.size(); i++) {
            jcbTipoPagamento.addItem(listaModelTipoPagamentos.get(i).getDescricao());
        }
    }

    private void limparCampos() {
        jtfSubtotal.setText("");
        jtfDesconto.setText("");
        jtfValorRecebido.setText("");
        jtfTroco.setText("");
        jcbTipoPagamento.setSelectedIndex(0);
        jlfValorPagar.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPagamentoPDV dialog = new ViewPagamentoPDV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox jcbTipoPagamento;
    private javax.swing.JLabel jlRS4;
    private javax.swing.JLabel jlfValorPagar;
    private javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfSubtotal;
    private javax.swing.JTextField jtfTroco;
    private javax.swing.JTextField jtfValorRecebido;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    /**
     * @return the valorTotal
     */
    public float getValorTotal() {
        return valorTotal;
    }

    /**
     * @param valorTotal the valorTotal to set
     */
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

    public void setTextFildValorTotal() {
        this.jtfSubtotal.setText(String.valueOf(this.valorTotal));
    }

    /**
     * @return the desconto
     */
    public float getDesconto() {
        return desconto;
    }

    /**
     * @param desconto the desconto to set
     */
    public void setDesconto(float desconto) {
        this.desconto = desconto;
    }

    /**
     * @return the valorRecebido
     */
    public float getValorRecebido() {
        return valorRecebido;
    }

    /**
     * @param valorRecebido the valorRecebido to set
     */
    public void setValorRecebido(float valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    /**
     * @return the troco
     */
    public float getTroco() {
        return troco;
    }

    /**
     * @param troco the troco to set
     */
    public void setTroco(float troco) {
        this.troco = troco;
    }

    /**
     * @return the totalPagar
     */
    public float getTotalPagar() {
        return totalPagar;
    }

    /**
     * @param totalPagar the totalPagar to set
     */
    public void setTotalPagar(float totalPagar) {
        this.totalPagar = totalPagar;
    }

    /**
     * @return the tipoPagamento
     */
    public String getTipoPagamento() {
        return tipoPagamento;
    }

    /**
     * @param tipoPagamento the tipoPagamento to set
     */
    public void setTipoPagamento(String tipoPagamento) {
        this.tipoPagamento = tipoPagamento;
    }
}
